apiVersion: apps/v1
kind: Deployment
metadata:
    name: albumranker
    namespace: albumranker
spec:
    selector:
        matchLabels:
            app: albumranker
    replicas: 2
    template:
        metadata:
            labels:
                app: albumranker
        spec:
            containers:
                # The <__IMAGE__> value is replaced with an image name during deployment (in .github/workflows/deploy.yml)
                - name: albumranker
                  image: <__IMAGE__>
                  ports:
                      - containerPort: 3000
