apiVersion: apps/v1
kind: Deployment
metadata:
    name: albumranker
    namespace: albumranker
spec:
    selector:
        matchLabels:
            app: albumranker
    replicas: 2
    template:
        metadata:
            labels:
                app: albumranker
        spec:
            containers:
                # The <__IMAGE__> value is replaced with an image name during deployment (in .github/workflows/deploy.yml)
                - name: albumranker
                  image: <__IMAGE__>
                  ports:
                      - containerPort: 3000
                  env:
                      - name: DATABASE_URL
                        valueFrom:
                            secretKeyRef:
                                name: albumranker
                                key: DATABASE_URL
                      - name: SIGNING_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: albumranker
                                key: SIGNING_SECRET
                      - name: SPOTIFY_CLIENT_ID
                        valueFrom:
                            secretKeyRef:
                                name: albumranker
                                key: SPOTIFY_CLIENT_ID
                      - name: SPOTIFY_CLIENT_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: albumranker
                                key: SPOTIFY_CLIENT_SECRET
                      - name: SPOTIFY_REDIRECT_URI
                        valueFrom:
                            secretKeyRef:
                                name: albumranker
                                key: SPOTIFY_REDIRECT_URI

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-production
spec:
    acme:
        email: safe.salt4183@fastmail.com
        server: https://acme-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
            name: letsencrypt-production
        solvers:
            - http01:
                  ingress:
                      class: nginx
